server:
  port: 9090
  metrics_path: /metrics
  health_path: /health

collection:
  interval: 60s
  timeout: 30s

aws:
  regions:
    - us-east-1
    - ap-south-1

cost_explorer:
  enabled: true
  frequency: hourly # hourly | daily | weekly | monthly

collectors:
  - apigateway
  - apigatewayv2
  - autoscaling
  - athena
  - mq
  - ses
  - cloudformation
  - documentdb
  - neptune
  - memorydb
  - timestream
  - fsx
  - backup
  - kinesis
  - firehose
  - kinesisanalytics
  - emr
  - elasticbeanstalk
  - kms
  - cloudtrail
  - batch
  - codebuild
  - codepipeline
  - codedeploy
  - ecr
  - ec2
  - efs
  - eventbridge
  - glue
  - apprunner
  - transfer
  - msk
  - redshift
  - s3
  - rds
  - lambda
  - ecs
  - elb
  - eks
  - dynamodb
  - elasticache
  - opensearch
  - guardduty
  - securityhub
  - inspector2
  - macie
  - waf
  - secretsmanager
  - sfn
  - ssm
  - sqs
  - sns
  - ebs
  - vpc
  - acm
  - cloudfront
  - route53
  - iam
  - shield

logging:
  level: info
  format: json
